### ISSUE TITLE
Add sql:index tag for creating indexes

### ISSUE THREAD

**Issue by eaigner** [eaigner/hood#2]
Add tag `sql:"index(foo)"` resulting in SQL `CREATE INDEX foo ON table_name (column_name)`

**Comment by cpisto** [comment]
How would you deal with multi column indexes? How about unique indexes?

**Comment by eaigner** [comment]
Haven't made my mind up yet, any suggestions welcome.

**Comment by lbolla** [comment]
I think that, in the long run, it would be better to have different types of struct "fields". "Column" would map to a DB table's column, "UniqueConstraint" would map to a unique constraint (possibly with multiple columns) on that table, etc.

For unique constraints on a single column, a simple struct tag "unique:true" would be enough.

Basically, I think of "taking inspiration" from sqlalchemy's declarative style (http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative.html)

**Comment by eaigner** [comment]
Constraints could implement a special Constraint interface, to separate them from the other fields

```
type User struct {
    Id                hood.Id
    Name              string `validate:"len(3:24)"`
    EncryptedPassword string `validate:"presence"`
    Joined            time.Time
    UniqueName        hood.UniqueConstraint // implements Constraint
}

type Constraint interface {
       // some methods...
}
```

**Comment by eaigner** [comment]
On the other hand, I don't really want to pollute the struct fields with "meta" information if it can be avoided.

**Comment by eaigner** [comment]
Maybe one single field would suffice where all constraints can be applied

```
type User struct {
    Id                hood.Id
    Name              string `validate:"len(3:24)"`
    EncryptedPassword string `validate:"presence"`
    Joined            time.Time
    Constraints       hood.Constraints `sql:"index(foo->col1+col2),unique(foo->col3+col4)"`
}
```

**Comment by eaigner** [comment]
I'll move that to the migration suite. It's really not a concern of the model.

**Comment by eaigner** [comment]
Implemented via `CreateIndex(3)` method.
