### ISSUE TITLE
Add quoting to dialect interface

### ISSUE THREAD

**Issue by coocood** [eaigner/hood#24]
The TestCreateTableSql case trying to create a column named "primary", I'm not sure it is intentionally or not, but this will not work in mysql, unless we wrap the talbe or column name with back quotes.

but the base dialect do not give a chance to wrap a table|column name with back quotes which means every method in it have to be rewritten for mysql dialect to support keyword table/columns.

What should I do?

**Comment by eaigner** [comment]
No, it was not intentional. If you wish to use quoted fields you have to pass them in manually at the moment, e.g. 

```
`"primary"`
```

**Comment by eaigner** [comment]
All identifiers are now quoted automatically (except in where clauses)
