### ISSUE TITLE
Null values cause a crash

### ISSUE THREAD

**Issue by iragsdale** [eaigner/hood#39]
Trying to select from a table with a null value will cause a crash.  Do something like this in SQL:

> create table test (a integer not null, b varchar);
> insert into test values (1, null);

Then with Hood, if you do this, you'll get a panic:

type Test struct {
  Id hood.Id
  Test string
}

vals := []Test{}
hd.FindSQL(&vals, "select \* from test")

That crashes consistently.

**Comment by iragsdale** [comment]
Oops, that should read hd.FindSQL(&vals, "select \* from test")

**Comment by iragsdale** [comment]
I feel like I did this wrong, but this commit appears to fix the issue locally with no adverse affects:

https://github.com/iragsdale/hood/commit/cc5b66f1d859b02d6aafd504de72f6660ec89a07

**Comment by eaigner** [comment]
A test case in `dialects_test.go` would have been nice. I'll pull this and add one soon.

**Comment by iragsdale** [comment]
Sorry, will add that next time - didn't occur to me, was just trying to avoid the crashes quickly. :)
