### ISSUE TITLE
A suggestion to simplify Indexes Add method.

### ISSUE THREAD

**Issue by coocood** [eaigner/hood#43]
Can we provide two methods for unique and non-unique index, like "Add" and "AddUnique", and remove the bool parameter. because pass bool parameter is harder to read.

And if no columns parameter is passed in, the index name will be considered as the single column name. this way we only need to pass in one parameter most of the time.

**Comment by eaigner** [comment]
Yes, I thought of removing the bool flag myself after I rewrote it to the new approach.

**Comment by eaigner** [comment]
Fixed in f13af4108e3a0fc21c23bfa0b913bede5ff0ac27

I hope I can stop breaking the API now, seems quite solid.
