### ISSUE TITLE
panic: CreateTable can only be invoked inside a transaction

### ISSUE THREAD

**Issue by zhenweiwang1990** [eaigner/hood#55]
I have move the CreateTable calling behind the `tx := hd.Begin()`,I still get an error 

```
panic: CreateTable can only be invoked inside a transaction
```

**Comment by eaigner** [comment]
That's because you do `hd.CreateTable(&Fruit{})` instead of `tx.CreateTable(&Fruit{})`

**Comment by d-reinhold** [comment]
I guess the real question is why does the example in the README use `hd.CreateTable(&Fruit{})` outside of the transaction scope? Is that no longer correct?

**Comment by eaigner** [comment]
When the table is created, no transaction has been started. Where do you see a declaration of `tx` before `hd.CreateTable`?

**Comment by d-reinhold** [comment]
It isn't, and when the example is run, it fails with this error: `panic: CreateTable can only be invoked inside a transaction`.

**Comment by eaigner** [comment]
Oh, I see. Must be a relic of the past.
