### ISSUE TITLE
Support sqlite dialect

### ISSUE THREAD

**Issue by lbolla** [eaigner/hood#6]
Support sqlite dialect. Maybe using: http://code.google.com/p/gosqlite/ or https://github.com/kuroneko/gosqlite3

**Comment by eaigner** [comment]
https://github.com/kuroneko/gosqlite3 is out of the race since it does not support the `database/sql` interface (for whatever reason I cannot understand).

**Comment by eaigner** [comment]
https://github.com/mattn/go-sqlite3 looks better
